# inherit_from: .rubocop_todo.yml

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'db/legacy_seeds.rb'
    - 'db/migrate/**/*.rb'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'spec/factories/**/*.rb'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
