---
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'db/legacy_seeds.rb'
    - 'db/migrate/**/*.rb'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'db/schema.rb'
  SupportedStyles:
    - single_quotes
    - double_quotes
