---
language: generic
sudo: required
services:
- docker
before_script:
- sudo /etc/init.d/postgresql stop
- make test-build
- docker-compose -f docker-compose.test.yml run web bundle exec rails db:test:prepare
script:
- make test-rspec
