language: ruby
bundler_args: --retry=3 --jobs=3
cache: bundler
sudo: false
rvm:
  - 2.6.0-preview2
  - 2.6.0-preview1
  - 2.5.3
  - ruby-head
matrix:
  allow_failures:
    - rvm:
      - ruby-head
      - 2.6.0-preview2
      - 2.6.0-preview1
  fast_finish: true
install:
  - bundle install
script:
  - bundle exec rspec
