addons:
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
  postgresql: '10.6'
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
bundler_args: --retry=3 --jobs=3
cache: bundler
dist: xenial
install:
  - bundle install
language: ruby
# matrix:
#   allow_failures:
#     - rvm:
#       - ruby-head
#       - 2.6.0-preview2
#       - 2.6.0-preview1
#   fast_finish: true
rvm:
  # - 2.6.0-preview2
  # - 2.6.0-preview1
  - 2.5.3
  # - ruby-head
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
sudo: false
