---
version: '3.4'
services:
  db:
    image: postgres
  db_test:
    image: postgres
  web:
    build: .
    command: bundle exec rerun --background "bundle exec rackup -p 3000 -o '0.0.0.0'"
    depends_on:
      - db
      - db_test
    entrypoint: ''
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      PGHOST: db
      PGUSER: postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
