---
version: '3.4'
services:
  db_test:
    image: postgres
  web:
    build: .
    command: bundle exec rspec
    depends_on:
      - db_test
    entrypoint: ''
    environment:
      RAILS_ENV: test
      RACK_ENV: test
      PGHOST: db_test
      PGUSER: postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
